on: [push]

env:
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  check_single_url:
    runs-on: ubuntu-latest
    name: Check a single URL
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check URLs
        uses: ./ # Uses an action in the root directory
